#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: ride-share-route
#          uri: ${RIDE_SHARE_ROUTE_URI:http://localhost:8081}

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8082
